# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

R:
  - oldrel
  - release
  - devel

os:
  - linux
  - osx

matrix:
  allow_failures:
    - r: oldrel
    - os: osx

repos:
  CRAN: https://cloud.r-project.org

warnings_are_errors: true

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
