# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages

r:
  - oldrel
  - release
  - devel

os:
  - linux
  - osx

r_packages:
  - knitr
  - rmarkdown
  - covr
  - lintr

matrix:
  allow_failures:
    - r: oldrel
    - os: osx

repos:
  CRAN: https://cloud.r-project.org

warnings_are_errors: true

after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'lintr::lint_package()'

notifications:
  email:
    on_success: change
    on_failure: change
